# Blog customization
title:            Alex Bashuk's blog
description:      Блог про життя та роботу у Лондоні
reading_time:     true
words_per_minute: 200
url:              http://alexbash.uk
baseurl:
background:
permalink:        /:categories/:title/
paginate:         5

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class
